version: "3.5"
services:
  develop:
    build: .
    container_name: fw-alerts-develop
    ports:
      - "4201:4201"
    environment:
      NODE_ENV: dev
      PORT: 4201
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: https://staging-api.resourcewatch.org
      ALERTS_API_URL: "https://staging-data-api.globalforestwatch.org"
      GLAD_ALERTS_API_URL: https://api.resourcewatch.org
      GFW_DATA_API_KEY: ${gfw_data_api_key}
      REDIS_URL: redis://redis:6379
    volumes:
      - ./app:/opt/fw-alerts/app
      - ./nodemon.json:/opt/fw-alerts/nodemon.json
    networks:
      - gfw-alerts-network
      - gfw-network
    command: yarn dev

  test:
    build: .
    container_name: fw-alerts-test
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: test
      PORT: 0
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: http://127.0.0.1:9000
      GLAD_ALERTS_API_URL: http://127.0.0.1:9000
    volumes:
      - ./app:/opt/fw-alerts/app
      - ./nodemon.json:/opt/fw-alerts/nodemon.json
      - ./jest.config.js:/opt/fw-alerts/jest.config.js
    command: yarn test

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - gfw-alerts-network

  docs:
    build: .
    ports:
      - "42010:42010"
    container_name: fw-alerts-docs
    volumes:
      - ./docs:/opt/fw-alerts/docs
    command: yarn run docs -l 42010

networks:
  gfw-alerts-network:
    name: gfw-alerts-network
  gfw-network:
    name: gfw-network
