version: "3.5"
services:
  develop:
    build: .
    container_name: fw-alerts-develop
    ports:
      - "4201:4201"
    environment:
      NODE_PATH: app/src
      NODE_ENV: dev
      PORT: 4201
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: https://api.resourcewatch.org
      GLAD_ALERTS_API_URL: https://api.resourcewatch.org
    volumes:
      - ./app:/opt/fw-alerts/app
    networks:
      - gfw-alerts-network
      - gfw-network
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js

  docs:
    build: .
    ports:
      - "42010:42010"
    container_name: fw-alerts-docs
    volumes:
      - ./docs:/opt/fw-alerts/docs
    command: yarn run docs -l 4201

networks:
  gfw-alerts-network:
    name: gfw-alerts-network
  gfw-network:
    name: gfw-network
