version: "3"
services:
  test:
    build: .
    container_name: fw-alerts-test
    ports:
      - "4200:4200"
    environment:
      NODE_PATH: app/src
      NODE_ENV: test
      PORT: 4200
      LOGGER_LEVEL: debug
      SUPPRESS_NO_CONFIG_WARNING: "true"
      CT_URL: http://127.0.0.1:9000
      GLAD_ALERTS_API_URL: http://127.0.0.1:9000
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js e2eTest
