version: "3.5"
services:
  develop:
    build: .
    container_name: fw-alerts-develop
    ports:
      - "4201:4201"
    environment:
      PORT: 4201
      NODE_PATH: app/src
      NODE_ENV: dev
      CONTROL_TOWER_URL: https://api.resourcewatch.org
      GLAD_ALERTS_API_URL: https://api.resourcewatch.org
    volumes:
      - ./app:/opt/fw-alerts/app
    networks:
      - gfw-alerts-network
      - gfw-network
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js

networks:
  gfw-alerts-network:
    name: gfw-alerts-network
  gfw-network:
    name: gfw-network
