apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: fw
  name: fw-alerts
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fw-alerts
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
