openapi: 3.1.0
info:
  title: fw_alerts
  version: '1.0'
  description: ''
  summary: API wrapper around WRI alerts service
servers:
  - url: 'https://fw-api.globalforestwatch.org'
    description: Production
  - url: 'https://staging-fw-api.globalforestwatch.org/'
    description: Staging
  - url: 'http://localhost:4201'
    description: Local
paths:
  '/fw-alerts/{dataset}/{geostore}':
    parameters:
      - schema:
          type: string
        name: dataset
        in: path
        required: true
      - schema:
          type: string
        name: geostore
        in: path
        required: true
    get:
      summary: Get Alerts By Geostore
      tags:
        - V1
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      operationId: get-alerts-by-geostore
      description: ''
      parameters:
        - schema:
            type: number
          in: query
          name: range
          description: Number of days in the past to fetch alerts from
        - schema:
            type: string
            enum:
              - csv
              - json
            default: json
          in: query
          name: output
  /fw_alerts/healthcheck:
    get:
      summary: Healthcheck
      tags:
        - V1
      responses:
        '200':
          $ref: '#/components/responses/Healthcheck'
      operationId: get-fw_api-healthcheck
      security: []
  '/v3/alerts/{geostoreId}':
    parameters:
      - schema:
          type: string
        name: geostoreId
        in: path
        required: true
    get:
      summary: Get geostore datasets
      tags:
        - V3
      responses:
        '200':
          $ref: '#/components/responses/Alerts'
        '401':
          $ref: '#/components/responses/Error'
      operationId: get-v3-alerts-geostoreId
      parameters:
        - schema:
            type: string
            enum:
              - GLAD
              - GLADS2
              - RADD
              - VIIRS
          in: query
          name: dataset
          required: true
          description: One or more datasets to query
        - schema:
            type: integer
          in: query
          name: minDate
          description: How many days ago to query
          required: true
      description: 'Endpoint to find one or more alert datasets for a given geostore. Multiple datasets can be queried as ?dataset=GLAD&dataset=VIIRS&dataset=RADD, etc. '
components:
  schemas:
    Alerts:
      title: Alerts
      x-stoplight:
        id: lmvzwf860gwzb
      type: object
      properties:
        latitude:
          type: string
        longitude:
          type: string
        date:
          type: string
        confidence:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  responses:
    Error:
      description: Error Response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              errors:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                    - status
                    - detail
                  properties:
                    status:
                      type: number
                    detail:
                      type: string
                      minLength: 1
            required:
              - errors
          examples: {}
    Healthcheck:
      description: Healthcheck response
      content:
        application/json:
          schema:
            type: object
            properties:
              uptime:
                type: number
          examples: {}
    Alerts:
      description: Array of alerts
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Alerts'
security:
  - Authorization: []
